# <center>『 파이토치 첫걸음 』</center>

<img src="https://www.hanbit.co.kr/data/books/B7818450418_l.jpg" width=30%>

---

# 6장. 순환 신경망

---

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#순환-신경망의-발달-과정" data-toc-modified-id="순환-신경망의-발달-과정-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>순환 신경망의 발달 과정</a></span></li><li><span><a href="#순환-신경망의-작동-원리" data-toc-modified-id="순환-신경망의-작동-원리-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>순환 신경망의 작동 원리</a></span></li><li><span><a href="#모델-구현,-학습-및-결과-확인" data-toc-modified-id="모델-구현,-학습-및-결과-확인-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>모델 구현, 학습 및 결과 확인</a></span></li><li><span><a href="#순환-신경망의-한계-및-개선-방안" data-toc-modified-id="순환-신경망의-한계-및-개선-방안-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>순환 신경망의 한계 및 개선 방안</a></span><ul class="toc-item"><li><span><a href="#LSTM" data-toc-modified-id="LSTM-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>LSTM</a></span></li><li><span><a href="#GRU" data-toc-modified-id="GRU-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>GRU</a></span></li></ul></li></ul></div>

--- 

## 순환 신경망의 발달 과정

**순환 신경망(Recurrent Neural Network, RNN)** 은 사실 합성곱 신경망보다 먼저 나온 신경망입니다. 1982년에 존 홉필드가 순환 신경망의 기본적인 형태를 대중화했다고 알려져 있지만, 해당 아이디어가 이때 처음 나온 것은 아니고 이전에도 언급된 적은 있다고 합니다.  
이때 만들어진 순환 신경망이 오늘날의 순환 신경망의 형태로 오기까지는 꽤 많은 시간이 걸렸습니다. 발전된 연산 능력과 데이터의 증가로 인해 성과를 보일 수 있게 된 것이죠. 특히 발전 과정에서 나온 **LSTM(Long Short-Term memory)** 과 **GRU(Gated Recurrent Unit)** 같은 변형 모델들은 오늘날에도 많이 사용되고 있습니다.  

- 시퀀스 데이터(sequence data): 순서가 존재하는 데이터
- 시계열 데이터(time series data): 순서가 존재하지만 특별히 시간에 따른 의미가 존재하는 데이터  

이처럼 순환 신경망은 **순서가 있는 데이터에서 의미를 찾아내기 위해 고안된 모델**이고, 자연스러운 발상인 동시에 중요성을 가집니다.

## 순환 신경망의 작동 원리

처음 순환 신경망을 공부할 때 모델을 도식화한 그림을 찾아보면 주로 이런 그림들이 나옵니다. 하지만 이런 그림은 잘 와 닿지 않을 수 있습니다. 아래에서 우리에게 익숙한 그림으로 차근차근 이해해보도록 하겠습니다.
<img src="https://iq.opengenus.org/content/images/2018/11/rnn.png" width=70%>

다음 그림은 3개의 입력이 들어와서 4개의 노드를 가진 은닉층 두 개를 거치는데, 여기서 노드를 1개로 바꾸면 다음 그림처럼 변합니다. 
<img src="https://mblogthumb-phinf.pstatic.net/MjAyMDAxMTlfMjg0/MDAxNTc5NDAxODAzMzE4.AGLcdLCMTum2ih-n1B8Jcru-Vdy0SWYbc5p5QEbzTJAg.bLER_lHl45pkXnb5mqiyVwv9IWIuIH3_fv61gAVAsLEg.PNG.audgnsdl115/SmartSelectImage_2020-01-19-11-43-01.png?type=w800" width=50%>

은닉층의 값이 다음번에 다시 해당 은닉층의 입력으로 들어가는 것을 볼 수 있습니다. 즉 t=1일 때 은닉층 각 노드의 값은 이전 시간(t=0)의 은닉층 값과 현재 시간(t=1)의 입력값의 조합으로 값이 계산된다고 할 수 있습니다. pytorch라는 단어를 예로 들면, 전에 p라는 단어가 들어왔었다는 것을 기억하고 있는 상태로 이번에 y가 들어왔을 때 다음에 나와야 할 알파벳이 무엇인지 예측하는 방식이라고 표현할 수 있습니다.
<img src="https://mblogthumb-phinf.pstatic.net/MjAyMDAxMTlfNTYg/MDAxNTc5NDEwMTk2OTU2.T1R8jOlvE0LR7nMx8-nehKDcPTDZi0V-oYzpzQnaa60g.vAVKlI4jfjpN1cteT_fVm2X5XBaB0CFJ8lX4nKc3ij0g.PNG.audgnsdl115/SmartSelectImage_2020-01-19-14-02-56.png?type=w800" width=50%>

이상을 정리하면 다음과 같습니다. 은닉층의 노드들은 어떠한 초깃값을 가지고 계산이 시작되고 첫 번째 입력값이 들어온 t=0 시점에서 입력값과 초깃값을 조합으로 은닉층의 값들이 계산되게 됩니다. 이 시점에서 결괏값이 도출되면, t=1 시점에서는 새로 들어온 입력값과 t=0 시점에서 계산된 은닉층의 값과의 조합으로 t=1일 때 은닉층의 값과 결괏값이 다시 계산됩니다. 이러한 과정이 지정한 시간만큼 반복됩니다.

일정 시간 동안 모든 값이 계산되면, **모델을 학습하기 위해** 결괏값과 목푯값의 차이를 손실 함수를 통해 계산하고 **역전파**해야하는데 기존의 역전파와 다르게 순환 신경망은 **계산에 사용된 시점의 수에 영향**을 받습니다. 예를 들어 t=0에서 t=2까지 계산에 사용됐다면 그 시간 전체에 대해 역전파를 해야 하는 것입니다. 이를 **시간에 따른 역전파(BackPropagation Through Time)** 라고 부릅니다.  

<img src="https://mblogthumb-phinf.pstatic.net/MjAyMDAxMTlfMjQy/MDAxNTc5NDM2MjkzNjUy.MdJJnpkO_bs4KlrP9--O62FtIUmqzBG7qoiZTBeriCQg.zXv9CM76hsAoaJS92oInTOIT_WvKN3PY6egO3y6vCrwg.PNG.audgnsdl115/SmartSelectImage_2020-01-19-21-17-25.png?type=w800" width=50%>  

이때 **모델을 학습**하려면 어떻게 해야 할까요?  
t=2의 시점에서 발생한 손실을 역전파하기 위해서는 손실을 입력과 은닉층들 사이의 가중치로 미분하여 손실에 대한 각각의 비중을 구해 업데이트하면 됩니다. 하지만 이 연산 과정에서 은닉층의 이전 시점의 값들이 연산에 포함되게 되는데 이전 시점의 값들은 내부적으로 다시 가중치, 입력값, 이전 시점의 값들의 조합으로 이루어져 있습니다. **순환 신경망은 각 위치별로 같은 가중치를 공유**하므로 t=2 시점의 손실을 역전파하기 위해서는 결과적으로 t=0 시점의 노드 값들에도 다 영향을 줘야 합니다. 즉 시간을 역으로 거슬러 올라가는 방식으로 각 가중치들을 업데이트해야 하기 때문에 시간에 따른 역전파라는 이름이 붙었습니다.

기본적으로 순환 신경망에서는 **하이퍼볼릭 탄젠트 활성화 함수**를 사용합니다. 수식을 살펴보면 다음과 같습니다.
<img src="https://blog.kakaocdn.net/dn/cE1r2x/btqY5LY6QVv/pJYdkSEI5t74WjqJrOh8Q1/img.png">

## 모델 구현, 학습 및 결과 확인

먼저 가장 기본적인 모델을 한번 만들어보겠습니다. 우선 필요한 라이브러리들을 불러옵니다.

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

이번 예시에서 사용할 문장은 **'hello pytorch. how long can a rnn cell remember?'** 라는 문장이고 사용할 문자들은 알파벳 소문자와 특수문자 몇 개로 한정하겠습니다.

In [5]:
n_hidden = 35 # 순환 신경망의 노드 수
lr = 0.01
epochs = 1000

string = "hello pytorch. how long can a rnn cell remember?"
chars = "abcdefghijklmnopqrstuvwxyz ?!.,:;01"
char_list = [i for i in chars]
n_letters = len(char_list)

다음으로는 문장이 들어왔을 때 이것을 원-핫 벡터로 바꾸는 함수를 하나 만들어보겠습니다. 어떤 문장이 들어왔을 때 맨 앞에 시작 토큰(start token)과 맨 뒤에 끝 토큰(end token)을 붙이고 원-핫 벡터로 변환하여 전달하는 함수입니다.

```python
# start
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])
# end
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
```

In [10]:
def string_to_onehot(string):
    
    start = np.zeros(shape=len(char_list), dtype=int)
    end = np.zeros(shape=len(char_list), dtype=int)
    start[-2] = 1
    end[-1] = 1
    
    for i in string:
        idx = char_list.index(i)
        zero = np.zeros(shape=n_letters, dtype=int)
        zero[idx]=1
        
        start = np.vstack([start,zero])
    
    output = np.vstack([start,end])
    
    return output

```python
# output
array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

len(string), len(chars): (48, 35)

string_to_onehot(string).shape: (50, 35)
```

원-핫 벡터를 다시 문자로 바꾸는 함수도 만들어놓으면 편하기 때문에 하나 만들어두겠습니다.

In [19]:
def onehot_to_word(onehot_1):

    # 텐서를 입력으로 받아 넘파이 배열로 바꿔준다.

    onehot = torch.Tensor.numpy(onehot_1)

    # one-hot 벡터의 최댓값(=1) 위치 인덱스로 문자를 찾는다.

    return char_list[onehot.argmax()]



In [21]:
onehot_to_word(torch.Tensor(start))

'0'

다음은 순환 신경망 클래스입니다.

In [30]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()
        
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        self.i2h = nn.Linear(input_size, hidden_size)
        self.h2h = nn.Linear(hidden_size, hidden_size)
        self.i2o = nn.Linear(hidden_size, output_size)
        self.act_fn = nn.Tanh()
        
    def forward(self, input, hidden):
        hidden = self.act_fn(self.i2h(input) + self.h2h(hidden))
        output = self.i2o(hidden)
        return output, hidden
    
    def init_hidden(self):
        return torch.zeros(1, self.hidden_size)

In [31]:
rnn = RNN(n_letters, n_hidden, n_letters) # 35, 35, 35

그다음에는 **손실 함수**와 **최적화 함수**를 정의하겠습니다. 이번에 사용할 **L2 손실 함수**는 **nn.MSELoss**로 구현되어 있습니다.

In [32]:
loss_func = nn.MSELoss()
optimizer = torch.optim.Adam(rnn.parameters(), lr=lr)

다음은 학습 부분입니다.

In [33]:
## training

one_hot = torch.from_numpy(string_to_onehot(string)).type_as(torch.FloatTensor())

for i in range(epochs):
    rnn.zero_grad()
    total_loss = 0
    hidden = rnn.init_hidden()

    for j in range(one_hot.size()[0]-1):
        input_ = one_hot[j:j+1,:]
        target = one_hot[j+1]
        
        output, hidden = rnn.forward(input_, hidden)
        loss = loss_func(output.view(-1),target.view(-1))
        total_loss += loss
        input_ = output

    total_loss.backward()
    optimizer.step()
    
    if i % 100 == 0:
        print(f'Epoch {i}\'s loss: {total_loss.item()}')

Epoch 0's loss: 2.284116268157959
Epoch 100's loss: 0.11178862303495407
Epoch 200's loss: 0.033989317715168
Epoch 300's loss: 0.022304633632302284
Epoch 400's loss: 0.014734550379216671
Epoch 500's loss: 0.014307282865047455
Epoch 600's loss: 0.011135882697999477
Epoch 700's loss: 0.010516466572880745
Epoch 800's loss: 0.0038819138426333666
Epoch 900's loss: 0.003132481360808015


모델을 학습한 이후에는 제대로 학습이 되었는지 확인해봐야 합니다. 지금은 간단한 예제이기 때문에 학습에 사용한 문장을 그대로 테스트에도 사용하겠습니다. 학습할 때는 단어 하나하나를 다 입력으로 넣어주었지만 테스트할 때는 첫 글자만 입력으로 전달하고 그 다음부터는 모델에서 나온 결괏값을 새로운 입력으로 전달하여, 첫 글자만으로 전체 문장을 생성해내는지를 확인해봅니다.

In [37]:
start = torch.zeros(1,len(char_list))
start[:,-2] = 1

with torch.no_grad():
    hidden = rnn.init_hidden()
    input_ = start
    output_string = ""
    for i in range(len(string)):
        output, hidden = rnn.forward(input_, hidden)
        output_string += onehot_to_word(output.data)
        input_ = output
        
print(output_string)

helloeeremhmannberll nne ber?1rany nbllllrraar a


 ## 순환 신경망의 한계 및 개선 방안

타임 시퀀스가 늘어나며 역전파 시 하이퍼볼릭 탄젠트 함수의 미분 값이 여러번 곱해지기 때문에 긴 문장에 대해 만족스러운 결과를 얻기가 힘들어집니다. 하이퍼볼릭 탄젠트 함수를 미분하면 0에서 1 사이의 값이 나오고, 기울기 값이 역전파될 때 타임 시퀀스가 길어질수록 모델이 제대로 학습을 하지 못하는 이른바 **기울기 소실(vanising gradient)** 이라는 현상이 일어나게 됩니다. 합성곱 신경망처럼 활성화 함수 등을 바꾸는 것도 하나의 개선 방법일 수 있지만, 개선 모델인 **LSTM**과 **GRU** 에서는 좀 다른 방법을 사용했습니다.

### LSTM

### GRU